version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    target-branch: dev
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - rust
    groups:
      tokio:
        patterns: ["tokio*"]
      sqlx:
        patterns: ["sqlx*"]
      tracing:
        patterns: ["tracing*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    target-branch: dev
    commit-message:
      prefix: "chore(ci)"
    labels:
      - dependencies
      - github-actions
